### ISSUE TITLE
need to unify monitor and openkb code and some openkb side bugs

### ISSUE THREAD

**Issue by zhongqin0820** [XiaoguTech/rta-monitor#5]
#### bugs in:
1. new a category(two category with same category id conflict)
2. new a panel(name conflict issues)

#### unify two system:
- [ ] need to modify monitor to fit the data structure in openkb

**Comment by zhongqin0820** [comment]
need to fix category display bugs and panel name conflict

**Comment by zhongqin0820** [comment]
fix all bugs but need to unify the user management

**Comment by Lee-Jiazheng** [comment]
What happened?
